name: mamang_app_flutter
description: "Mobile App Marketing and Gaming"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  change_case: ^2.1.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_markdown: ^0.7.4
  flutter_screenutil: ^5.9.3
  flutter_sticky_header: ^0.7.0
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  get: ^4.6.6
  photo_view: ^0.15.0
  pinput: ^5.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/logos/
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
