import 'package:mamang_app_flutter/models/img_api.dart';

class Promotion {
  int id;
  int userId;
  String name;
  String thumb;
  String category;
  String desc;
  double distance;
  double price;
  String location;
  String date;
  bool verified;
  bool published;
  int stared;
  String type;
  double xp;
  int level;
  bool saved;
  bool? liked;

  Promotion({
    this.id = 0,
    this.userId = 0,
    this.name = '',
    this.thumb = '',
    this.category = '',
    this.desc = '',
    this.distance = 0,
    this.price = 0,
    this.location = '',
    this.date = '',
    this.verified = false,
    this.published = false,
    this.stared = 0,
    this.saved = false,
    this.type = '',
    this.xp = 0,
    this.level = 0,
    this.liked,
  });
}

final List<Promotion> promoList = [
  Promotion(
    id: 1,
    userId: 1,
    name: 'drive 24/365 eyeballs',
    thumb: ImgApi.photo[1],
    category: 'automotive',
    desc: 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    distance: 70,
    price: 54,
    location: '8 Esch Terrace',
    date: '16/01/2025',
    verified: false,
    published: false,
    stared: 34,
    type: 'purple',
    xp: 571,
    level: 76,
    saved: false
  ),
  Promotion(
    id: 2,
    userId: 4,
    name: 'monetize B2B schemas',
    thumb: ImgApi.photo[51],
    category: 'education',
    desc: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',
    distance: 66,
    price: 86,
    location: '1 Old Gate Drive',
    date: '27/12/2024',
    verified: false,
    published: true,
    stared: 5,
    type: 'purple',
    xp: 568,
    level: 23,
    saved: false
  ),
  Promotion(
    id: 3,
    userId: 10,
    name: 'repurpose efficient action-items',
    thumb: ImgApi.photo[31],
    category: 'automotive',
    desc: 'Pellentesque ultrices mattis odio. Donec vitae nisi.',
    distance: 9,
    price: 85,
    location: '5 Acker Alley',
    date: '22/03/2024',
    verified: false,
    published: true,
    stared: 29,
    type: 'grey',
    xp: 628,
    level: 97,
    saved: false
  ),
  Promotion(
    id: 4,
    userId: 2,
    name: 'e-enable bricks-and-clicks platforms',
    thumb: ImgApi.photo[71],
    category: 'holiday',
    desc: 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    distance: 1,
    price: 50,
    location: '21 Arkansas Alley',
    date: '04/06/2024',
    verified: false,
    published: false,
    stared: 74,
    type: 'green',
    xp: 629,
    level: 31,
    saved: false
  ),
  Promotion(
    id: 5,
    userId: 8,
    name: 'engage integrated synergies',
    thumb: ImgApi.photo[32],
    category: 'automotive',
    desc: 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.',
    distance: 58,
    price: 21,
    location: '181 Packers Plaza',
    date: '14/07/2024',
    verified: true,
    published: false,
    stared: 12,
    type: 'grey',
    xp: 197,
    level: 0,
    saved: false
  ),
  Promotion(
    id: 6,
    userId: 9,
    name: 'optimize robust markets',
    thumb: ImgApi.photo[33],
    category: 'automotive',
    desc: 'Pellentesque eget nunc.',
    distance: 97,
    price: 43,
    location: '6 Maple Parkway',
    date: '15/01/2025',
    verified: true,
    published: false,
    stared: 49,
    type: 'blue',
    xp: 948,
    level: 74,
    saved: false,
    liked: true,
  ),
  Promotion(
    id: 7,
    userId: 5,
    name: 'exploit holistic channels',
    thumb: ImgApi.photo[1],
    category: 'food',
    desc: 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.',
    distance: 94,
    price: 21,
    location: '82 Autumn Leaf Parkway',
    date: '22/05/2024',
    verified: true,
    published: true,
    stared: 44,
    type: 'blue',
    xp: 814,
    level: 61,
    saved: false
  ),
  Promotion(
    id: 8,
    userId: 9,
    name: 'reintermediate compelling e-services',
    thumb: ImgApi.photo[8],
    category: 'services',
    desc: 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.',
    distance: 91,
    price: 8,
    location: '70 Starling Plaza',
    date: '06/02/2025',
    verified: true,
    published: false,
    stared: 59,
    type: 'blue',
    xp: 898,
    level: 98,
    saved: false
  ),
  Promotion(
    id: 9,
    userId: 9,
    name: 'engage mission-critical schemas',
    thumb: ImgApi.photo[52],
    category: 'education',
    desc: 'Nam nulla.',
    distance: 9,
    price: 95,
    location: '7134 Carberry Alley',
    date: '23/09/2024',
    verified: true,
    published: false,
    stared: 34,
    type: 'grey',
    xp: 670,
    level: 3,
    saved: false
  ),
  Promotion(
    id: 10,
    userId: 9,
    name: 'productize end-to-end markets',
    thumb: ImgApi.photo[61],
    category: 'sport',
    desc: 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',
    distance: 12,
    price: 97,
    location: '681 Becker Lane',
    date: '15/10/2024',
    verified: true,
    published: false,
    stared: 25,
    type: 'blue',
    xp: 673,
    level: 58,
    saved: false,
    liked: true,
  ),
  Promotion(
    id: 11,
    userId: 5,
    name: 'iterate viral web-readiness',
    thumb: ImgApi.photo[21],
    category: 'services',
    desc: 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
    distance: 80,
    price: 7,
    location: '201 3rd Hill',
    date: '09/08/2024',
    verified: false,
    published: false,
    stared: 14,
    type: 'grey',
    xp: 591,
    level: 75,
    saved: false
  ),
  Promotion(
    id: 12,
    userId: 10,
    name: 'deliver sticky convergence',
    thumb: ImgApi.photo[62],
    category: 'sport',
    desc: 'Pellentesque at nulla. Suspendisse potenti.',
    distance: 8,
    price: 6,
    location: '86 Mallard Parkway',
    date: '28/11/2024',
    verified: false,
    published: true,
    stared: 33,
    type: 'green',
    xp: 678,
    level: 99,
    saved: false
  ),
  Promotion(
    id: 13,
    userId: 8,
    name: 'engineering advenced platforms',
    thumb: ImgApi.photo[53],
    category: 'education',
    desc: 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.',
    distance: 82,
    price: 11,
    location: '5 Bashford Junction',
    date: '29/05/2024',
    verified: true,
    published: false,
    stared: 69,
    type: 'green',
    xp: 786,
    level: 92,
    saved: false,
    liked: true,
  ),
  Promotion(
    id: 14,
    userId: 8,
    name: 'revolutionize web-enabled functionalities',
    thumb: ImgApi.photo[91],
    category: 'souvenir',
    desc: 'In blandit ultrices enim.',
    distance: 85,
    price: 55,
    location: '4 Eagan Junction',
    date: '19/07/2024',
    verified: true,
    published: false,
    stared: 58,
    type: 'green',
    xp: 299,
    level: 2,
    saved: false
  ),
  Promotion(
    id: 15,
    userId: 7,
    name: 'orchestrate one-to-one e-services',
    thumb: ImgApi.photo[22],
    category: 'services',
    desc: 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    distance: 61,
    price: 37,
    location: '83 Rowland Parkway',
    date: '19/11/2024',
    verified: true,
    published: true,
    stared: 21,
    type: 'purple',
    xp: 24,
    level: 70,
    saved: false
  ),
  Promotion(
    id: 16,
    userId: 1,
    name: 'architect frictionless e-commerce',
    thumb: ImgApi.photo[72],
    category: 'holiday',
    desc: 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
    distance: 71,
    price: 57,
    location: '84539 Sheridan Plaza',
    date: '06/08/2024',
    verified: true,
    published: false,
    stared: 11,
    type: 'green',
    xp: 696,
    level: 25,
    saved: true
  ),
  Promotion(
    id: 17,
    userId: 9,
    name: 'utilize robust experiences',
    thumb: ImgApi.photo[63],
    category: 'sport',
    desc: 'In quis justo. Maecenas rhoncus aliquam lacus.',
    distance: 81,
    price: 18,
    location: '04 Meadow Vale Park',
    date: '11/09/2024',
    verified: false,
    published: false,
    stared: 29,
    type: 'grey',
    xp: 538,
    level: 22,
    saved: false
  ),
  Promotion(
    id: 18,
    userId: 2,
    name: 'enable integrated partnerships',
    thumb: ImgApi.photo[23],
    category: 'services',
    desc: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.',
    distance: 13,
    price: 56,
    location: '403 Tony Avenue',
    date: '10/12/2024',
    verified: true,
    published: false,
    stared: 70,
    type: 'grey',
    xp: 728,
    level: 80,
    saved: false,
    liked: true,
  ),
  Promotion(
    id: 19,
    userId: 1,
    name: 'recontextualize one-to-one communities',
    thumb: ImgApi.photo[44],
    category: 'property',
    desc: 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    distance: 28,
    price: 42,
    location: '74970 Declaration Plaza',
    date: '27/10/2024',
    verified: false,
    published: true,
    stared: 27,
    type: 'purple',
    xp: 401,
    level: 46,
    saved: false
  ),
  Promotion(
    id: 20,
    userId: 10,
    name: 'monetize customized portals',
    thumb: ImgApi.photo[41],
    category: 'property',
    desc: 'Nulla tempus.',
    distance: 18,
    price: 13,
    location: '189 Sugar Place',
    date: '28/03/2024',
    verified: false,
    published: true,
    stared: 45,
    type: 'green',
    xp: 866,
    level: 65,
    saved: true
  ),
  Promotion(
    id: 21,
    userId: 7,
    name: 'streamline real-time partnerships',
    thumb: ImgApi.photo[24],
    category: 'services',
    desc: 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.',
    distance: 98,
    price: 26,
    location: '39833 Tennyson Terrace',
    date: '02/11/2024',
    verified: false,
    published: true,
    stared: 61,
    type: 'blue',
    xp: 221,
    level: 19,
    saved: false
  ),
  Promotion(
    id: 22,
    userId: 4,
    name: 'envisioneer cross-media relationships',
    thumb: ImgApi.photo[42],
    category: 'property',
    desc: 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',
    distance: 15,
    price: 42,
    location: '432 Superior Plaza',
    date: '04/10/2024',
    verified: false,
    published: true,
    stared: 23,
    type: 'purple',
    xp: 468,
    level: 24,
    saved: false,
    liked: true,
  ),
  Promotion(
    id: 23,
    userId: 9,
    name: 'evolve customized applications',
    thumb: ImgApi.photo[92],
    category: 'souvenir',
    desc: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    distance: 69,
    price: 26,
    location: '5 Canary Pass',
    date: '20/08/2024',
    verified: true,
    published: true,
    stared: 23,
    type: 'grey',
    xp: 201,
    level: 3,
    saved: true
  ),
  Promotion(
    id: 24,
    userId: 3,
    name: 'enhance killer e-services',
    thumb: ImgApi.photo[43],
    category: 'property',
    desc: 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    distance: 4,
    price: 59,
    location: '917 Towne Pass',
    date: '26/03/2024',
    verified: false,
    published: false,
    stared: 6,
    type: 'green',
    xp: 960,
    level: 79,
    saved: false,
    liked: true
  ),
  Promotion(
    id: 25,
    userId: 2,
    name: 'revolutionize wireless partnerships',
    thumb: ImgApi.photo[73],
    category: 'holiday',
    desc: 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    distance: 4,
    price: 70,
    location: '43 Coleman Point',
    date: '15/12/2024',
    verified: true,
    published: false,
    stared: 43,
    type: 'grey',
    xp: 575,
    level: 11,
    saved: false
  ),
  Promotion(
    id: 26,
    userId: 10,
    name: 'monetize integrated schemas',
    thumb: ImgApi.photo[34],
    category: 'automotive',
    desc: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',
    distance: 44,
    price: 18,
    location: '26 Gateway Crossing',
    date: '24/09/2024',
    verified: true,
    published: true,
    stared: 12,
    type: 'green',
    xp: 691,
    level: 78,
    saved: false
  ),
  Promotion(
    id: 27,
    userId: 8,
    name: 'engineer one-to-one ROI',
    thumb: ImgApi.photo[64],
    category: 'sport',
    desc: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.',
    distance: 69,
    price: 93,
    location: '68 Goodland Street',
    date: '15/05/2024',
    verified: true,
    published: true,
    stared: 81,
    type: 'grey',
    xp: 105,
    level: 16,
    saved: false
  ),
  Promotion(
    id: 28,
    userId: 7,
    name: 'aggregate clicks-and-mortar relationships',
    thumb: ImgApi.photo[2],
    category: 'food',
    desc: 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',
    distance: 23,
    price: 25,
    location: '725 Corben Alley',
    date: '08/05/2024',
    verified: false,
    published: true,
    stared: 85,
    type: 'green',
    xp: 484,
    level: 61,
    saved: true
  ),
  Promotion(
    id: 29,
    userId: 5,
    name: 'exploit visionary systems',
    thumb: ImgApi.photo[65],
    category: 'sport',
    desc: 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',
    distance: 68,
    price: 42,
    location: '28023 La Follette Terrace',
    date: '26/01/2025',
    verified: false,
    published: true,
    stared: 40,
    type: 'blue',
    xp: 613,
    level: 33,
    saved: false
  ),
  Promotion(
    id: 30,
    userId: 4,
    name: 'brand synergistic channels',
    thumb: ImgApi.photo[66],
    category: 'sport',
    desc: 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.',
    distance: 100,
    price: 45,
    location: '74330 Redwing Parkway',
    date: '23/05/2024',
    verified: true,
    published: true,
    stared: 68,
    type: 'blue',
    xp: 98,
    level: 52,
    saved: false
  ),
  Promotion(
    id: 31,
    userId: 1,
    name: 'reinvent interactive web services',
    thumb: ImgApi.photo[67],
    category: 'sport',
    desc: 'Vivamus vel nulla eget eros elementum pellentesque.',
    distance: 27,
    price: 43,
    location: '709 Reindahl Point',
    date: '17/05/2024',
    verified: false,
    published: true,
    stared: 85,
    type: 'blue',
    xp: 56,
    level: 57,
    saved: false
  ),
  Promotion(
    id: 32,
    userId: 5,
    name: 'disintermediate seamless e-markets',
    thumb: ImgApi.photo[54],
    category: 'education',
    desc: 'Nullam molestie nibh in lectus. Pellentesque at nulla.',
    distance: 98,
    price: 80,
    location: '3113 Meadow Ridge Street',
    date: '16/08/2024',
    verified: true,
    published: true,
    stared: 29,
    type: 'green',
    xp: 426,
    level: 88,
    saved: false
  ),
  Promotion(
    id: 33,
    userId: 4,
    name: 'incentivize impactful solutions',
    thumb: ImgApi.photo[55],
    category: 'education',
    desc: 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.',
    distance: 78,
    price: 13,
    location: '0257 Sunnyside Drive',
    date: '11/06/2024',
    verified: false,
    published: false,
    stared: 87,
    type: 'green',
    xp: 99,
    level: 61,
    saved: false
  ),
  Promotion(
    id: 34,
    userId: 6,
    name: 'streamline sticky mindshare',
    thumb: ImgApi.photo[93],
    category: 'souvenir',
    desc: 'In hac habitasse platea dictumst.',
    distance: 60,
    price: 37,
    location: '17842 Sunbrook Parkway',
    date: '14/02/2024',
    verified: false,
    published: true,
    stared: 96,
    type: 'purple',
    xp: 363,
    level: 90,
    saved: false
  ),
  Promotion(
    id: 35,
    userId: 1,
    name: 'maximize interactive e-tailers',
    thumb: ImgApi.photo[94],
    category: 'souvenir',
    desc: 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
    distance: 60,
    price: 25,
    location: '8988 Oriole Plaza',
    date: '26/10/2024',
    verified: false,
    published: false,
    stared: 14,
    type: 'blue',
    xp: 120,
    level: 59,
    saved: true
  ),
  Promotion(
    id: 36,
    userId: 4,
    name: 'embrace integrated web services',
    thumb: ImgApi.photo[35],
    category: 'automotive',
    desc: 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.',
    distance: 62,
    price: 18,
    location: '4890 Calypso Place',
    date: '09/08/2024',
    verified: true,
    published: false,
    stared: 73,
    type: 'green',
    xp: 115,
    level: 13,
    saved: false
  ),
  Promotion(
    id: 37,
    userId: 9,
    name: 'exploit vertical systems',
    thumb: ImgApi.photo[3],
    category: 'food',
    desc: 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    distance: 24,
    price: 16,
    location: '931 Pearson Court',
    date: '11/07/2024',
    verified: false,
    published: true,
    stared: 78,
    type: 'grey',
    xp: 958,
    level: 67,
    saved: false,
    liked: true,
  ),
  Promotion(
    id: 38,
    userId: 1,
    name: 'drive turn-key solutions',
    thumb: ImgApi.photo[38],
    category: 'education',
    desc: 'Duis bibendum. Morbi non quam nec dui luctus rutrum.',
    distance: 86,
    price: 76,
    location: '56 Bowman Avenue',
    date: '23/05/2024',
    verified: false,
    published: false,
    stared: 92,
    type: 'green',
    xp: 108,
    level: 26,
    saved: false
  ),
  Promotion(
    id: 39,
    userId: 3,
    name: 'matrix clicks-and-mortar mindshare',
    thumb: ImgApi.photo[39],
    category: 'education',
    desc: 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    distance: 6,
    price: 55,
    location: '31 Bonner Junction',
    date: '28/10/2024',
    verified: false,
    published: true,
    stared: 75,
    type: 'blue',
    xp: 54,
    level: 83,
    saved: false
  ),
  Promotion(
    id: 40,
    userId: 7,
    name: 'embrace cross-media architectures',
    thumb: ImgApi.photo[4],
    category: 'food',
    desc: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    distance: 56,
    price: 98,
    location: '50515 New Castle Park',
    date: '10/12/2024',
    verified: true,
    published: true,
    stared: 48,
    type: 'blue',
    xp: 257,
    level: 51,
    saved: true
  ),
  Promotion(
    id: 41,
    userId: 1,
    name: 'implement viral interfaces',
    thumb: ImgApi.photo[74],
    category: 'holiday',
    desc: 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.',
    distance: 86,
    price: 6,
    location: '2 4th Center',
    date: '12/01/2025',
    verified: true,
    published: false,
    stared: 24,
    type: 'purple',
    xp: 192,
    level: 4,
    saved: false
  ),
  Promotion(
    id: 42,
    userId: 8,
    name: 'engineer killer platforms',
    thumb: ImgApi.photo[56],
    category: 'education',
    desc: 'Morbi non quam nec dui luctus rutrum.',
    distance: 95,
    price: 79,
    location: '11 Warrior Circle',
    date: '29/05/2024',
    verified: true,
    published: true,
    stared: 83,
    type: 'blue',
    xp: 717,
    level: 70,
    saved: false
  ),
  Promotion(
    id: 43,
    userId: 2,
    name: 'enable leading-edge technologies',
    thumb: ImgApi.photo[36],
    category: 'automotive',
    desc: 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
    distance: 93,
    price: 56,
    location: '8094 Judy Crossing',
    date: '18/05/2024',
    verified: true,
    published: true,
    stared: 72,
    type: 'grey',
    xp: 922,
    level: 89,
    saved: false
  ),
  Promotion(
    id: 44,
    userId: 8,
    name: 'deploy efficient methodologies',
    thumb: ImgApi.photo[57],
    category: 'education',
    desc: 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    distance: 6,
    price: 67,
    location: '59505 Sugar Avenue',
    date: '06/04/2024',
    verified: true,
    published: false,
    stared: 53,
    type: 'purple',
    xp: 294,
    level: 3,
    saved: false
  ),
  Promotion(
    id: 45,
    userId: 9,
    name: 'harness e-business ROI',
    thumb: ImgApi.photo[25],
    category: 'services',
    desc: 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',
    distance: 53,
    price: 94,
    location: '5435 Bellgrove Hill',
    date: '07/06/2024',
    verified: true,
    published: false,
    stared: 46,
    type: 'blue',
    xp: 384,
    level: 11,
    saved: false
  ),
  Promotion(
    id: 46,
    userId: 8,
    name: 'benchmark turn-key synergies',
    thumb: ImgApi.photo[37],
    category: 'automotive',
    desc: 'Maecenas tincidunt lacus at velit.',
    distance: 10,
    price: 49,
    location: '5961 Charing Cross Park',
    date: '25/03/2024',
    verified: true,
    published: true,
    stared: 2,
    type: 'green',
    xp: 517,
    level: 61,
    saved: true
  ),
  Promotion(
    id: 47,
    userId: 1,
    name: 'transform innovative portals',
    thumb: ImgApi.photo[47],
    category: 'property',
    desc: 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',
    distance: 22,
    price: 98,
    location: '59293 Gina Drive',
    date: '25/02/2024',
    verified: true,
    published: true,
    stared: 97,
    type: 'purple',
    xp: 577,
    level: 19,
    saved: false
  ),
  Promotion(
    id: 48,
    userId: 3,
    name: 'drive dot-com schemas',
    thumb: ImgApi.photo[6],
    category: 'food',
    desc: 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    distance: 98,
    price: 73,
    location: '04594 Coolidge Avenue',
    date: '10/09/2024',
    verified: true,
    published: false,
    stared: 75,
    type: 'blue',
    xp: 253,
    level: 42,
    saved: false
  ),
  Promotion(
    id: 49,
    userId: 10,
    name: 'seize intuitive convergence',
    thumb: ImgApi.photo[95],
    category: 'souvenir',
    desc: 'Etiam justo. Etiam pretium iaculis justo.',
    distance: 72,
    price: 27,
    location: '2927 Carpenter Street',
    date: '17/11/2024',
    verified: false,
    published: false,
    stared: 94,
    type: 'green',
    xp: 458,
    level: 87,
    saved: false
  ),
  Promotion(
    id: 50,
    userId: 9,
    name: 'unleash seamless infomediaries',
    thumb: ImgApi.photo[8],
    category: 'food',
    desc: 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
    distance: 34,
    price: 80,
    location: '39 International Plaza',
    date: '25/09/2024',
    verified: false,
    published: true,
    stared: 61,
    type: 'green',
    xp: 602,
    level: 92,
    saved: false
  ),
  Promotion(
    id: 51,
    userId: 6,
    name: 'deploy e-business web services',
    thumb: ImgApi.photo[68],
    category: 'sport',
    desc: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    distance: 50,
    price: 11,
    location: '7 Arkansas Lane',
    date: '18/02/2024',
    verified: true,
    published: false,
    stared: 38,
    type: 'purple',
    xp: 353,
    level: 86,
    saved: true
  ),
  Promotion(
    id: 52,
    userId: 5,
    name: 'iterate interactive paradigms',
    thumb: ImgApi.photo[52],
    category: 'education',
    desc: 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    distance: 37,
    price: 99,
    location: '7175 Carpenter Circle',
    date: '16/04/2024',
    verified: false,
    published: false,
    stared: 51,
    type: 'blue',
    xp: 870,
    level: 33,
    saved: true
  ),
  Promotion(
    id: 53,
    userId: 3,
    name: 'benchmark wireless bandwidth',
    thumb: ImgApi.photo[69],
    category: 'sport',
    desc: 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
    distance: 85,
    price: 73,
    location: '67299 Stang Pass',
    date: '23/10/2024',
    verified: false,
    published: false,
    stared: 5,
    type: 'green',
    xp: 565,
    level: 9,
    saved: false
  ),
  Promotion(
    id: 54,
    userId: 10,
    name: 'strategize ubiquitous networks',
    thumb: ImgApi.photo[45],
    category: 'property',
    desc: 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.',
    distance: 59,
    price: 42,
    location: '3 Raven Place',
    date: '22/01/2025',
    verified: false,
    published: true,
    stared: 68,
    type: 'blue',
    xp: 480,
    level: 65,
    saved: false
  ),
  Promotion(
    id: 55,
    userId: 10,
    name: 'benchmark holistic channels',
    thumb: ImgApi.photo[75],
    category: 'holiday',
    desc: 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.',
    distance: 11,
    price: 77,
    location: '25 Gina Drive',
    date: '09/01/2025',
    verified: true,
    published: true,
    stared: 21,
    type: 'purple',
    xp: 577,
    level: 42,
    saved: false
  ),
  Promotion(
    id: 56,
    userId: 7,
    name: 'orchestrate real-time architectures',
    thumb: ImgApi.photo[58],
    category: 'education',
    desc: 'Pellentesque ultrices mattis odio. Donec vitae nisi.',
    distance: 98,
    price: 84,
    location: '46677 7th Road',
    date: '09/10/2024',
    verified: false,
    published: true,
    stared: 85,
    type: 'grey',
    xp: 472,
    level: 98,
    saved: false
  ),
  Promotion(
    id: 57,
    userId: 7,
    name: 'morph wireless schemas',
    thumb: ImgApi.photo[38],
    category: 'automotive',
    desc: 'Praesent blandit. Nam nulla.',
    distance: 76,
    price: 61,
    location: '9 Anthes Road',
    date: '09/03/2024',
    verified: true,
    published: true,
    stared: 24,
    type: 'green',
    xp: 114,
    level: 0,
    saved: true
  ),
  Promotion(
    id: 58,
    userId: 6,
    name: 'iterate open-source architectures',
    thumb: ImgApi.photo[76],
    category: 'holiday',
    desc: 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.',
    distance: 33,
    price: 2,
    location: '813 Linden Park',
    date: '13/11/2024',
    verified: true,
    published: true,
    stared: 60,
    type: 'grey',
    xp: 895,
    level: 3,
    saved: false
  ),
  Promotion(
    id: 59,
    userId: 4,
    name: 'maximize seamless bandwidth',
    thumb: ImgApi.photo[26],
    category: 'services',
    desc: 'Aliquam non mauris.',
    distance: 100,
    price: 65,
    location: '0 Vidon Place',
    date: '09/10/2024',
    verified: true,
    published: true,
    stared: 15,
    type: 'blue',
    xp: 297,
    level: 44,
    saved: false
  ),
  Promotion(
    id: 60,
    userId: 10,
    name: 'empower granular infomediaries',
    thumb: ImgApi.photo[27],
    category: 'services',
    desc: 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    distance: 84,
    price: 98,
    location: '61534 Longview Lane',
    date: '21/05/2024',
    verified: false,
    published: true,
    stared: 48,
    type: 'blue',
    xp: 866,
    level: 22,
    saved: false
  ),
  Promotion(
    id: 61,
    userId: 6,
    name: 'optimize plug-and-play applications',
    thumb: ImgApi.photo[96],
    category: 'souvenir',
    desc: 'Nullam molestie nibh in lectus. Pellentesque at nulla.',
    distance: 61,
    price: 43,
    location: '9860 Hoffman Place',
    date: '27/05/2024',
    verified: false,
    published: false,
    stared: 56,
    type: 'green',
    xp: 777,
    level: 47,
    saved: false
  ),
  Promotion(
    id: 62,
    userId: 4,
    name: 'monetize viral interfaces',
    thumb: ImgApi.photo[70],
    category: 'sport',
    desc: 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    distance: 87,
    price: 66,
    location: '824 Dakota Hill',
    date: '16/05/2024',
    verified: false,
    published: false,
    stared: 54,
    type: 'blue',
    xp: 229,
    level: 47,
    saved: false
  ),
  Promotion(
    id: 63,
    userId: 4,
    name: 'seize leading-edge channels',
    thumb: ImgApi.photo[63],
    category: 'services',
    desc: 'Mauris ullamcorper purus sit amet nulla.',
    distance: 61,
    price: 89,
    location: '9542 Dottie Crossing',
    date: '25/12/2024',
    verified: false,
    published: true,
    stared: 79,
    type: 'green',
    xp: 436,
    level: 19,
    saved: true
  ),
  Promotion(
    id: 64,
    userId: 10,
    name: 'optimize real-time portals',
    thumb: ImgApi.photo[97],
    category: 'souvenir',
    desc: 'Cras pellentesque volutpat dui.',
    distance: 85,
    price: 18,
    location: '5 Waxwing Place',
    date: '21/05/2024',
    verified: false,
    published: false,
    stared: 65,
    type: 'purple',
    xp: 702,
    level: 93,
    saved: false
  ),
  Promotion(
    id: 65,
    userId: 9,
    name: 'streamline mission-critical applications',
    thumb: ImgApi.photo[11],
    category: 'food',
    desc: 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',
    distance: 35,
    price: 9,
    location: '06116 Maryland Lane',
    date: '23/02/2024',
    verified: true,
    published: true,
    stared: 60,
    type: 'purple',
    xp: 228,
    level: 92,
    saved: false
  ),
  Promotion(
    id: 66,
    userId: 10,
    name: 'expedite sticky networks',
    thumb: ImgApi.photo[77],
    category: 'holiday',
    desc: 'Vivamus tortor.',
    distance: 94,
    price: 81,
    location: '9424 Artisan Lane',
    date: '14/06/2024',
    verified: false,
    published: false,
    stared: 7,
    type: 'green',
    xp: 342,
    level: 20,
    saved: false
  ),
  Promotion(
    id: 67,
    userId: 5,
    name: 'grow significant ROI',
    thumb: ImgApi.photo[39],
    category: 'automotive',
    desc: 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    distance: 85,
    price: 50,
    location: '39 Transport Street',
    date: '24/12/2024',
    verified: false,
    published: true,
    stared: 72,
    type: 'grey',
    xp: 985,
    level: 44,
    saved: false
  ),
  Promotion(
    id: 68,
    userId: 5,
    name: 'repurpose 24/365 technologies',
    thumb: ImgApi.photo[40],
    category: 'services',
    desc: 'In sagittis dui vel nisl. Duis ac nibh.',
    distance: 83,
    price: 74,
    location: '00 Hollow Ridge Place',
    date: '08/07/2024',
    verified: true,
    published: true,
    stared: 84,
    type: 'blue',
    xp: 411,
    level: 24,
    saved: false
  ),
  Promotion(
    id: 69,
    userId: 3,
    name: 'empower transparent convergence',
    thumb: ImgApi.photo[35],
    category: 'automotive',
    desc: 'Quisque ut erat. Curabitur gravida nisi at nibh.',
    distance: 47,
    price: 38,
    location: '503 Graceland Point',
    date: '12/04/2024',
    verified: false,
    published: true,
    stared: 49,
    type: 'green',
    xp: 969,
    level: 81,
    saved: true
  ),
  Promotion(
    id: 70,
    userId: 6,
    name: 'benchmark innovative niches',
    thumb: ImgApi.photo[29],
    category: 'services',
    desc: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
    distance: 18,
    price: 63,
    location: '28803 Division Center',
    date: '05/12/2024',
    verified: true,
    published: false,
    stared: 14,
    type: 'purple',
    xp: 311,
    level: 46,
    saved: false
  ),
  Promotion(
    id: 71,
    userId: 7,
    name: 'revolutionize robust e-business',
    thumb: ImgApi.photo[78],
    category: 'holiday',
    desc: 'Suspendisse ornare consequat lectus.',
    distance: 33,
    price: 80,
    location: '843 Nancy Drive',
    date: '15/10/2024',
    verified: true,
    published: true,
    stared: 15,
    type: 'purple',
    xp: 221,
    level: 90,
    saved: true
  ),
  Promotion(
    id: 72,
    userId: 2,
    name: 'seize clicks-and-mortar e-markets',
    thumb: ImgApi.photo[79],
    category: 'holiday',
    desc: 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
    distance: 61,
    price: 76,
    location: '46937 Blue Bill Park Pass',
    date: '07/05/2024',
    verified: false,
    published: false,
    stared: 90,
    type: 'purple',
    xp: 769,
    level: 79,
    saved: false
  ),
  Promotion(
    id: 73,
    userId: 7,
    name: 'engage visionary e-commerce',
    thumb: ImgApi.photo[12],
    category: 'food',
    desc: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    distance: 60,
    price: 71,
    location: '6286 Lakewood Drive',
    date: '11/03/2024',
    verified: true,
    published: false,
    stared: 16,
    type: 'grey',
    xp: 11,
    level: 14,
    saved: false
  ),
  Promotion(
    id: 74,
    userId: 5,
    name: 'morph extensible methodologies',
    thumb: ImgApi.photo[59],
    category: 'education',
    desc: 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.',
    distance: 46,
    price: 5,
    location: '903 Jenna Parkway',
    date: '18/04/2024',
    verified: true,
    published: true,
    stared: 24,
    type: 'purple',
    xp: 392,
    level: 88,
    saved: true
  ),
  Promotion(
    id: 75,
    userId: 3,
    name: 'synergize holistic architectures',
    thumb: ImgApi.photo[30],
    category: 'services',
    desc: 'Nam tristique tortor eu pede.',
    distance: 93,
    price: 32,
    location: '8 Blaine Court',
    date: '04/07/2024',
    verified: false,
    published: false,
    stared: 40,
    type: 'green',
    xp: 297,
    level: 25,
    saved: false
  ),
  Promotion(
    id: 76,
    userId: 10,
    name: 'synergize interactive ROI',
    thumb: ImgApi.photo[98],
    category: 'souvenir',
    desc: 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    distance: 43,
    price: 100,
    location: '9840 Pepper Wood Terrace',
    date: '13/12/2024',
    verified: true,
    published: false,
    stared: 18,
    type: 'grey',
    xp: 831,
    level: 16,
    saved: false
  ),
  Promotion(
    id: 77,
    userId: 6,
    name: 'unleash best-of-breed supply-chains',
    thumb: ImgApi.photo[60],
    category: 'education',
    desc: 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    distance: 92,
    price: 14,
    location: '74 Hoard Court',
    date: '15/08/2024',
    verified: false,
    published: false,
    stared: 62,
    type: 'blue',
    xp: 562,
    level: 66,
    saved: false
  ),
  Promotion(
    id: 78,
    userId: 1,
    name: 'redefine open-source systems',
    thumb: ImgApi.photo[80],
    category: 'holiday',
    desc: 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
    distance: 25,
    price: 85,
    location: '78 Waywood Circle',
    date: '26/09/2024',
    verified: false,
    published: false,
    stared: 41,
    type: 'green',
    xp: 371,
    level: 61,
    saved: false
  ),
  Promotion(
    id: 79,
    userId: 6,
    name: 'orchestrate efficient synergies',
    thumb: ImgApi.photo[36],
    category: 'automotive',
    desc: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    distance: 57,
    price: 86,
    location: '61529 Columbus Circle',
    date: '01/09/2024',
    verified: true,
    published: false,
    stared: 21,
    type: 'grey',
    xp: 718,
    level: 49,
    saved: false
  ),
  Promotion(
    id: 80,
    userId: 8,
    name: 'brand customized web-readiness',
    thumb: ImgApi.photo[48],
    category: 'property',
    desc: 'Sed sagittis.',
    distance: 8,
    price: 64,
    location: '69383 Amoth Drive',
    date: '30/08/2024',
    verified: false,
    published: true,
    stared: 20,
    type: 'green',
    xp: 978,
    level: 95,
    saved: false
  ),
  Promotion(
    id: 81,
    userId: 1,
    name: 'incentivize best-of-breed functionalities',
    thumb: ImgApi.photo[99],
    category: 'souvenir',
    desc: 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    distance: 65,
    price: 100,
    location: '30810 Canary Hill',
    date: '31/01/2025',
    verified: true,
    published: false,
    stared: 79,
    type: 'blue',
    xp: 869,
    level: 11,
    saved: false
  ),
  Promotion(
    id: 82,
    userId: 4,
    name: 'mesh web-enabled e-services',
    thumb: ImgApi.photo[82],
    category: 'sport',
    desc: 'Nam dui.',
    distance: 47,
    price: 1,
    location: '209 Banding Trail',
    date: '19/02/2024',
    verified: true,
    published: false,
    stared: 49,
    type: 'blue',
    xp: 999,
    level: 2,
    saved: false
  ),
  Promotion(
    id: 83,
    userId: 9,
    name: 'recontextualize compelling systems',
    thumb: ImgApi.photo[37],
    category: 'automotive',
    desc: 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    distance: 11,
    price: 46,
    location: '4836 Park Meadow Plaza',
    date: '28/09/2024',
    verified: false,
    published: true,
    stared: 68,
    type: 'green',
    xp: 405,
    level: 68,
    saved: true
  ),
  Promotion(
    id: 84,
    userId: 7,
    name: 'empower frictionless paradigms',
    thumb: ImgApi.photo[38],
    category: 'automotive',
    desc: 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',
    distance: 32,
    price: 32,
    location: '034 Green Terrace',
    date: '18/11/2024',
    verified: true,
    published: false,
    stared: 82,
    type: 'grey',
    xp: 427,
    level: 46,
    saved: false
  ),
  Promotion(
    id: 85,
    userId: 3,
    name: 'embrace clicks-and-mortar applications',
    thumb: ImgApi.photo[31],
    category: 'services',
    desc: 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',
    distance: 56,
    price: 26,
    location: '659 Tony Place',
    date: '28/10/2024',
    verified: false,
    published: false,
    stared: 7,
    type: 'green',
    xp: 287,
    level: 95,
    saved: true
  ),
  Promotion(
    id: 86,
    userId: 8,
    name: 'grow distributed initiatives',
    thumb: ImgApi.photo[14],
    category: 'food',
    desc: 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',
    distance: 77,
    price: 18,
    location: '91 Claremont Drive',
    date: '09/06/2024',
    verified: true,
    published: false,
    stared: 11,
    type: 'grey',
    xp: 631,
    level: 23,
    saved: false
  ),
  Promotion(
    id: 87,
    userId: 8,
    name: 'empower value-added solutions',
    thumb: ImgApi.photo[39],
    category: 'automotive',
    desc: 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    distance: 84,
    price: 86,
    location: '297 High Crossing Junction',
    date: '20/09/2024',
    verified: true,
    published: false,
    stared: 71,
    type: 'green',
    xp: 237,
    level: 84,
    saved: false
  ),
  Promotion(
    id: 88,
    userId: 3,
    name: 'generate revolutionary networks',
    thumb: ImgApi.photo[88],
    category: 'holiday',
    desc: 'Cras pellentesque volutpat dui.',
    distance: 6,
    price: 68,
    location: '7008 Red Cloud Plaza',
    date: '27/10/2024',
    verified: false,
    published: false,
    stared: 81,
    type: 'purple',
    xp: 616,
    level: 2,
    saved: false
  ),
  Promotion(
    id: 89,
    userId: 9,
    name: 'revolutionize plug-and-play architectures',
    thumb: ImgApi.photo[50],
    category: 'property',
    desc: 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    distance: 23,
    price: 79,
    location: '89320 Twin Pines Alley',
    date: '13/04/2024',
    verified: true,
    published: false,
    stared: 37,
    type: 'green',
    xp: 959,
    level: 91,
    saved: false
  ),
  Promotion(
    id: 90,
    userId: 1,
    name: 'benchmark dynamic synergies',
    thumb: ImgApi.photo[90],
    category: 'sport',
    desc: 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',
    distance: 12,
    price: 43,
    location: '935 Parkside Court',
    date: '14/02/2024',
    verified: false,
    published: true,
    stared: 66,
    type: 'grey',
    xp: 1,
    level: 97,
    saved: false
  ),
  Promotion(
    id: 91,
    userId: 2,
    name: 'cultivate e-business web services',
    thumb: ImgApi.photo[40],
    category: 'automotive',
    desc: 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',
    distance: 9,
    price: 79,
    location: '1471 Vermont Terrace',
    date: '13/01/2025',
    verified: true,
    published: true,
    stared: 8,
    type: 'purple',
    xp: 900,
    level: 41,
    saved: true
  ),
  Promotion(
    id: 92,
    userId: 6,
    name: 'aggregate leading-edge convergence',
    thumb: ImgApi.photo[15],
    category: 'food',
    desc: 'Duis at velit eu est congue elementum.',
    distance: 12,
    price: 98,
    location: '8989 Old Gate Lane',
    date: '15/02/2024',
    verified: true,
    published: false,
    stared: 94,
    type: 'grey',
    xp: 635,
    level: 20,
    saved: true
  ),
  Promotion(
    id: 93,
    userId: 8,
    name: 'empower next-generation e-commerce',
    thumb: ImgApi.photo[17],
    category: 'food',
    desc: 'Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    distance: 1,
    price: 12,
    location: '62801 Kennedy Road',
    date: '06/03/2024',
    verified: false,
    published: true,
    stared: 35,
    type: 'blue',
    xp: 601,
    level: 14,
    saved: false
  ),
  Promotion(
    id: 94,
    userId: 4,
    name: 'recontextualize user-centric functionalities',
    thumb: ImgApi.photo[94],
    category: 'souvenir',
    desc: 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.',
    distance: 21,
    price: 91,
    location: '26756 Boyd Avenue',
    date: '02/05/2024',
    verified: true,
    published: false,
    stared: 83,
    type: 'blue',
    xp: 153,
    level: 78,
    saved: false
  ),
  Promotion(
    id: 95,
    userId: 2,
    name: 'engage customized users',
    thumb: ImgApi.photo[32],
    category: 'automotive',
    desc: 'Etiam faucibus cursus urna.',
    distance: 24,
    price: 30,
    location: '40 Butterfield Hill',
    date: '14/08/2024',
    verified: true,
    published: false,
    stared: 10,
    type: 'grey',
    xp: 175,
    level: 85,
    saved: false
  ),
  Promotion(
    id: 96,
    userId: 3,
    name: 'optimize 24/7 web-readiness',
    thumb: ImgApi.photo[32],
    category: 'services',
    desc: 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
    distance: 53,
    price: 36,
    location: '9 Maryland Park',
    date: '02/12/2024',
    verified: true,
    published: true,
    stared: 32,
    type: 'green',
    xp: 106,
    level: 71,
    saved: false
  ),
  Promotion(
    id: 97,
    userId: 10,
    name: 'whiteboard cross-platform e-markets',
    thumb: ImgApi.photo[100],
    category: 'souvenir',
    desc: 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.',
    distance: 38,
    price: 69,
    location: '8 Schiller Lane',
    date: '15/11/2024',
    verified: true,
    published: true,
    stared: 52,
    type: 'green',
    xp: 195,
    level: 12,
    saved: false
  ),
  Promotion(
    id: 98,
    userId: 3,
    name: 'aggregate real-time web-readiness',
    thumb: ImgApi.photo[33],
    category: 'services',
    desc: 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',
    distance: 23,
    price: 73,
    location: '33 Bashford Alley',
    date: '06/01/2025',
    verified: false,
    published: false,
    stared: 76,
    type: 'green',
    xp: 434,
    level: 17,
    saved: false
  ),
  Promotion(
    id: 99,
    userId: 5,
    name: 'seize absolute e-services',
    thumb: ImgApi.photo[99],
    category: '29',
    desc: 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.',
    distance: 7,
    price: 55,
    location: '2 American Crossing',
    date: '20/02/2024',
    verified: true,
    published: false,
    stared: 20,
    type: 'blue',
    xp: 285,
    level: 91,
    saved: false
  ),
  Promotion(
    id: 100,
    userId: 1,
    name: 'evolve magnetic partnerships',
    thumb: ImgApi.photo[100],
    category: 'education',
    desc: 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
    distance: 62,
    price: 48,
    location: '879 Logan Lane',
    date: '12/06/2024',
    verified: true,
    published: false,
    stared: 25,
    type: 'grey',
    xp: 219,
    level: 92,
    saved: false
  )
];
