import 'package:mamang_app_flutter/models/img_api.dart';
import 'package:mamang_app_flutter/models/users.dart';

final List<User> rankList = [
  User(
    id: 1,
    name: 'Jean Doe',
    distance: 4,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[6],
    coin: 200,
    point: 100,
  ),
  User(
    id: 2,
    name: 'John Doe',
    distance: 1.5,
    title: 'premium',
    status: 'active',
    avatar: ImgApi.avatar[0],
    coin: 190,
    point: 90,
  ),
  User(
    id: 3,
    name: 'Jena Doe',
    distance: 5,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[1],
    coin: 180,
    point: 80,
  ),
  User(
    id: 4,
    name: 'James Doe',
    distance: 0.5,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[7],
    coin: 140,
    point: 10,
  ),
  User(
    id: 5,
    name: 'Jack Doe',
    distance: 1,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[8],
    coin: 110,
    point: 5,
  ),
  User(
    id: 6,
    name: 'Jean Doe',
    distance: 4,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[6],
    coin: 98,
    point: 100,
  ),
  User(
    id: 7,
    name: 'John Doe',
    distance: 1.5,
    title: 'premium',
    status: 'active',
    avatar: ImgApi.avatar[0],
    coin: 95,
    point: 90,
  ),
  User(
    id: 8,
    name: 'Jena Doe',
    distance: 5,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[1],
    coin: 80,
    point: 80,
  ),
  User(
    id: 9,
    name: 'James Doe',
    distance: 0.5,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[7],
    coin: 70,
    point: 10,
  ),
  User(
    id: 10,
    name: 'Jack Doe',
    distance: 1,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[8],
    coin: 60,
    point: 5,
  ),
  User(
    id: 11,
    name: 'Jean Doe',
    distance: 4,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[6],
    coin: 50,
    point: 100,
  ),
  User(
    id: 12,
    name: 'John Doe',
    distance: 1.5,
    title: 'premium',
    status: 'active',
    avatar: ImgApi.avatar[0],
    coin: 40,
    point: 90,
  ),
  User(
    id: 13,
    name: 'Jena Doe',
    distance: 5,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[1],
    coin: 30,
    point: 80,
  ),
  User(
    id: 14,
    name: 'James Doe',
    distance: 0.5,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[7],
    coin: 40,
    point: 10,
  ),
  User(
    id: 15,
    name: 'Jack Doe',
    distance: 1,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[8],
    coin: 10,
    point: 5,
  ),
  User(
    id: 16,
    name: 'Jean Doe',
    distance: 4,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[6],
    coin: 8,
    point: 100,
  ),
  User(
    id: 17,
    name: 'John Doe',
    distance: 1.5,
    title: 'premium',
    status: 'active',
    avatar: ImgApi.avatar[0],
    coin: 8,
    point: 90,
  ),
  User(
    id: 18,
    name: 'Jena Doe',
    distance: 5,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[1],
    coin: 8,
    point: 80,
  ),
  User(
    id: 19,
    name: 'James Doe',
    distance: 0.5,
    title: 'regular',
    status: 'active',
    avatar: ImgApi.avatar[7],
    coin: 4,
    point: 10,
  ),
  User(
    id: 20,
    name: 'Jack Doe',
    distance: 1,
    title: 'VIP',
    status: 'non-active',
    avatar: ImgApi.avatar[8],
    coin: 1,
    point: 5,
  ),
];